# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Florabis/florabis.github.io
  branch: main
  auth_type: pkce
  app_id: Ov23liVj5p7ONzeJ79RC

media_folder: /media
public_folder: /public

collections:
  - name: posts
    label: Posts
    folder: /content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }