# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Florabis/florabis.github.io
  branch: main

media_folder: /docs/public/media
public_folder: /docs/media

collections:
  - name: guide
    label: Guide
    folder: docs/guide
    fields:
      - { label: Body, name: body, widget: markdown }
  - name: gov
    label: Government
    files:
#      - name: officials
#        label: Officials
#        file: docs/gov/officials.md
#        fields:
#          - { label: Title, name: title, widget: string }
#          - { label: Body, name: body, widget: markdown }

      - name: constitution
        label: Constitution
        file: docs/gov/constitution.md
        fields:
          - { label: Title, name: title, widget: string, readonly: true }
          - { label: Body, name: body, widget: markdown }

      - name: laws-general
        label: Laws – General
        file: docs/gov/laws/general.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - name: laws-citizenship
        label: Laws – Citizenship
        file: docs/gov/laws/citizenship.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - name: laws-property
        label: Laws – Property
        file: docs/gov/laws/property.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - name: laws-economy
        label: Laws – Economy
        file: docs/gov/laws/economy.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - name: laws-crime
        label: Laws – Crime
        file: docs/gov/laws/crime.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - name: bills
        label: Bills
        file: docs/gov/bills.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

singletons:
  - file: docs/.vitepress/site.json
    label: VitePress site config
    name: site
    format: raw
    editor:
      preview: false
    fields:
      - name: body
        label: Config
        widget: code
        output_code_only: true
        allow_language_selection: false
        default_language: json
